# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class RunSummaryQuery(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['run_summary']] = None
    start_date: typing.Optional[str] = Field(default=None, description='Start date in YYYY-MM-DD format')
    end_date: typing.Optional[str] = Field(default=None, description='End date in YYYY-MM-DD format')
    with_dog: typing.Optional[bool] = Field(default=None, description='True for runs with Laika, False for solo')

class ShoeMileageQuery(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['shoe_mileage']] = None
    shoe_id: typing.Optional[int] = Field(default=None, description='Specific shoe ID, null for all shoes')
    active_only: typing.Optional[bool] = Field(default=None, description='Filter to only active (not retired) shoes')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
