# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (2)
# #########################################################################

class RunSummaryQuery(BaseModel):
    intent: typing_extensions.Literal['run_summary']
    start_date: str = Field(description='Start date in YYYY-MM-DD format')
    end_date: str = Field(description='End date in YYYY-MM-DD format')
    with_dog: bool = Field(description='True for runs with Laika, False for solo')

class ShoeMileageQuery(BaseModel):
    intent: typing_extensions.Literal['shoe_mileage']
    shoe_id: typing.Optional[int] = Field(default=None, description='Specific shoe ID, null for all shoes')
    active_only: bool = Field(description='Filter to only active (not retired) shoes')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
